import 'package:flutter/material.dart';
class HistoryPage extends StatefulWidget {
  const HistoryPage({super.key});

  @override
  State<HistoryPage> createState() => _HistoryPageState();
}

class _HistoryPageState extends State<HistoryPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.grey[900],
        bottom: PreferredSize(preferredSize:  Size.fromHeight(150),
         child: Center(
           child: Row(children: [
         Padding(padding: const EdgeInsets.fromLTRB(90, 0, 0, 200)),
         InkWell(onTap: (){},
         child: Container(height: 50,
         width: 50,
         decoration: BoxDecoration(color: Color.fromARGB(255, 24, 23, 23),
           borderRadius: BorderRadius.circular(20),
           ),
           child: Icon(Icons.arrow_left,
           color: Colors.white,),
           ),
           ),
           Padding(padding: const EdgeInsets.fromLTRB(90, 0, 0, 200)),
           Text("History",
           style: TextStyle(color: Colors.white,
           fontSize: 24,
           fontWeight: FontWeight.w800,),),
            Padding(padding: const EdgeInsets.fromLTRB(90, 0, 0, 200)),
InkWell(onTap: (){},
         child: Container(height: 50,
         width: 50,
         decoration: BoxDecoration(color: Color.fromARGB(255, 24, 23, 23),
           borderRadius: BorderRadius.circular(20),
           ),
           child: Icon(Icons.delete,
           color: Colors.white,),
           ),
           ),
                 ],),
         ),
        ),
      ),
      body: ListView(children: 
      [Padding(padding: const EdgeInsets.all(10)),
        Row(
          children: [Padding(padding: const EdgeInsets.only(left:30),),
            SizedBox(height:42 ,
            width: 530,
              child: TextField(
                      decoration: InputDecoration
                      (border: OutlineInputBorder(borderRadius: BorderRadius.circular(20),
                      ),
            focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(20),
              borderSide: BorderSide(color: Colors.grey,
              ),
            ),
            prefixIcon: Icon(Icons.search,
            color: Colors.green,
            size: 30,
            ),
            hintText: 'Search here ..',
            hintStyle: TextStyle(color: Colors.white,),
            suffixIcon: IconButton(onPressed: (){}, icon:  Icon(Icons.keyboard_voice_rounded,
            color: Colors.white,),),
            
            // filled: true,
            // fillColor: Colors.white,
                      ),
                    ),
            ),
          ],
        ),
        Padding(padding: const EdgeInsets.all(5)),
        Container(height:149 ,
        width: 343,
        margin: EdgeInsets.all(15),
        decoration: BoxDecoration(color:Color.fromARGB(255, 24, 23, 23),
         borderRadius: BorderRadius.circular(10),
         border: Border.all(color:Color.fromARGB(255, 24, 23, 23),)
          ),
         child: Column(
           children: [Padding(padding: const EdgeInsets.only(top: 15),),
             Row(children: [
              Padding(padding: const EdgeInsets.only(left: 18),),
              // Container(decoration: BoxDecoration(shape: BoxShape.circle
              // ),
              // child: Image.asset("assets/circlegreen.jpg") ,
              // ),
              Icon(Icons.mode_standby,
              color: Colors.green[400],),
               Padding(padding: const EdgeInsets.only(left: 15),),
               Text("7958 Swift Village",
               style: TextStyle(color: Colors.white,
               fontSize: 17,
               fontWeight: FontWeight.w400),),
             ],),
              // Image.asset("assets/line.jpg") ,
              Padding(padding: const EdgeInsets.only(top: 15),),
              Row(children: [ Padding(padding: const EdgeInsets.only(left: 15),),
                Icon(Icons.location_on,
              color: Colors.red[800],),
               Padding(padding: const EdgeInsets.only(left: 15),),
               Text("105 William St, Chicago, US",
               style: TextStyle(color: Colors.white,
                fontSize: 17,
               fontWeight: FontWeight.w400),),
              ],),
                  Padding(padding: const EdgeInsets.only(top: 15),),
               Divider(color:Colors.grey,
                  thickness: 1,
                  height: 1,
                  endIndent: 30,
                  indent: 30,),
                   Padding(padding: const EdgeInsets.only(top: 8),),
                   Row(children: [
                     Padding(padding: const EdgeInsets.only(left: 15),),
                     Container(
                      decoration: BoxDecoration(shape: BoxShape.circle,
                     color: Colors.grey,
                     ),
                     child:  Icon(Icons.monetization_on_sharp,
              color: Colors.white,),),
               
               Padding(padding: const EdgeInsets.only(left: 10),),
               Text("\$75.00",
               style: TextStyle(color: Colors.white,
                fontSize: 17,
               fontWeight: FontWeight.w400),),
               Padding(padding: const EdgeInsets.only(left: 350)),
               Text("Confirm",
               style: TextStyle(color: Color(0xff4252FF),
                fontSize: 15,
               fontWeight: FontWeight.w400),),
               IconButton(onPressed: (){}, icon:  Icon(Icons.arrow_right,
               color: Colors.white,))
             
              ],),
           ],
         ),
        ),
       
        Container(height:149 ,
        width: 343,
        margin: EdgeInsets.all(15),
        decoration: BoxDecoration(color:Color.fromARGB(255, 24, 23, 23),
         borderRadius: BorderRadius.circular(10),
          ),
         child: Column(
           children: [Padding(padding: const EdgeInsets.only(top: 15),),
             Row(children: [
              Padding(padding: const EdgeInsets.only(left: 20),),
              // Container(decoration: BoxDecoration(shape: BoxShape.circle
              // ),
              // child: Image.asset("assets/circlegreen.jpg") ,
              // ),
              Icon(Icons.mode_standby,
              color: Colors.green[400],),
               Padding(padding: const EdgeInsets.only(left: 15),),
               Text("026 Mitchell Burg Apt. 574",
               style: TextStyle(color: Colors.white,
                fontSize: 17,
               fontWeight: FontWeight.w400),),
             ],),
              // Image.asset("assets/line.jpg") ,
              Padding(padding: const EdgeInsets.only(top: 15),),
              Row(children: [ Padding(padding: const EdgeInsets.only(left: 15),),
                Icon(Icons.location_on,
              color: Colors.red[800],),
               Padding(padding: const EdgeInsets.only(left: 15),),
               Text("324 Lottie Views Suite 426",
               style: TextStyle(color: Colors.white,
                fontSize: 17,
               fontWeight: FontWeight.w400),),
              ],),
                  Padding(padding: const EdgeInsets.only(top: 15),),
               Divider(color:Colors.grey,
                  thickness: 1,
                  height: 1,
                  endIndent: 30,
                  indent: 30,),
                   Padding(padding: const EdgeInsets.only(top: 8),),
                   Row(children: [
                     Padding(padding: const EdgeInsets.only(left: 15),),
                     Container(
                      decoration: BoxDecoration(shape: BoxShape.circle,
                     color: Colors.grey,
                     ),
                     child:  Icon(Icons.monetization_on_sharp,
              color: Colors.white,),),
               
               Padding(padding: const EdgeInsets.only(left: 10),),
               Text("\$30.00",
               style: TextStyle(color: Colors.white,
                fontSize: 17,
               fontWeight: FontWeight.w400),),
               Padding(padding: const EdgeInsets.only(left: 330)),
               Text("Completed",
               style: TextStyle(color: Color(0xff03DE73),
                fontSize: 15,
               fontWeight: FontWeight.w400),),
               IconButton(onPressed: (){}, icon:  Icon(Icons.arrow_right,
               color: Colors.white,))
             
              ],),
           ],
         ),
        ),
          
        Container(height:149 ,
        width: 343,
        margin: EdgeInsets.all(15),
        decoration: BoxDecoration(color:Color.fromARGB(255, 24, 23, 23),
         borderRadius: BorderRadius.circular(10),
          ),
         child: Column(
           children: [Padding(padding: const EdgeInsets.only(top: 20),),
             Row(children: [
              Padding(padding: const EdgeInsets.only(left: 15),),
           
              Icon(Icons.mode_standby,
              color: Colors.green[400],),
               Padding(padding: const EdgeInsets.only(left: 15),),
               Text("89 Stacy Falls Suite 953",
               style: TextStyle(color: Colors.white,
                fontSize: 17,
               fontWeight: FontWeight.w400),),
             ],),
              // Image.asset("assets/line.jpg") ,
              Padding(padding: const EdgeInsets.only(top: 15),),
              Row(children: [ Padding(padding: const EdgeInsets.only(left: 15),),
                Icon(Icons.location_on,
              color: Colors.red[800],),
               Padding(padding: const EdgeInsets.only(left: 15),),
               Text("080 Joaquin Isle Suite 865",
               style: TextStyle(color: Colors.white,
                fontSize: 17,
               fontWeight: FontWeight.w400),),
              ],),
                  Padding(padding: const EdgeInsets.only(top: 15),),
               Divider(color:Colors.grey,
                  thickness: 1,
                  height: 1,
                  endIndent: 30,
                  indent: 30,),
                   Padding(padding: const EdgeInsets.only(top: 8),),
                   Row(children: [
                     Padding(padding: const EdgeInsets.only(left: 15),),
                     Container(
                      decoration: BoxDecoration(shape: BoxShape.circle,
                     color: Colors.grey,
                     ),
                     child:  Icon(Icons.monetization_on_sharp,
              color: Colors.white,),),
               
               Padding(padding: const EdgeInsets.only(left: 10),),
               Text("\$35.00",
               style: TextStyle(color: Colors.white,
                fontSize: 17,
               fontWeight: FontWeight.w400),),
               Padding(padding: const EdgeInsets.only(left: 330)),
               Text("Cancelled",
               style: TextStyle(color: Color(0xffC8C7CC),
                fontSize: 15,
               fontWeight: FontWeight.w400),),
               IconButton(onPressed: (){}, icon:  Icon(Icons.arrow_right,
               color: Colors.white,))
             
              ],),
           ],
         ),
        ),
      ],),
    );
  }
}